import type { CellValue, UploadedDataset } from "../ingestion/types.ts";
import { findColumnByRole } from "../universal/headers.ts";
import { periodTime } from "../universal/profile.ts";
import type { EntityActivity, EventGroup, EventSemantics, EventTransactionAnalysis, NormalizedEvent, RepeatedPattern } from "./types.ts";

export const EVENT_WINDOW_MS = 300_000 as const;
const present = (value: CellValue | undefined) => value !== null && value !== undefined && String(value).trim() !== "";
const round = (value: number) => Math.round(value * 1e12) / 1e12;
const median = (values: number[]) => { const sorted = [...values].sort((a, b) => a - b), middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; };
const percentile = (values: number[], fraction: number) => { const sorted = [...values].sort((a, b) => a - b); return sorted[Math.floor((sorted.length - 1) * fraction)]; };
export function stableStringify(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stableStringify(item)}`).join(",")}}`; return JSON.stringify(value); }
export function stableHash(value: unknown): string { const text = stableStringify(value); let hash = 2166136261; for (let i = 0; i < text.length; i += 1) { hash ^= text.charCodeAt(i); hash = Math.imul(hash, 16777619); } return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`; }

export function resolveEventSemantics(dataset: UploadedDataset): EventSemantics {
  const timestampColumn = findColumnByRole(dataset.columns, "EVENT_TIMESTAMP");
  const eventTypeColumn = findColumnByRole(dataset.columns, "EVENT_TYPE");
  if (!timestampColumn || !eventTypeColumn) throw new Error("Event semantics require timestamp and event type columns.");
  return { eventIdColumn: findColumnByRole(dataset.columns, "EVENT_ID") ?? null, timestampColumn, entityColumn: findColumnByRole(dataset.columns, "ENTITY_ID") ?? null, eventTypeColumn, valueColumn: findColumnByRole(dataset.columns, "EVENT_VALUE") ?? null };
}
export function normalizeEvents(dataset: UploadedDataset, semantics = resolveEventSemantics(dataset)): NormalizedEvent[] {
  return dataset.rows.map((row, index) => ({ sourceRow: index + 1, eventId: semantics.eventIdColumn && present(row[semantics.eventIdColumn]) ? String(row[semantics.eventIdColumn]) : `ROW-${index + 1}`, entityId: semantics.entityColumn && present(row[semantics.entityColumn]) ? String(row[semantics.entityColumn]) : "ALL_EVENTS", timestamp: String(row[semantics.timestampColumn]), timeMs: periodTime(row[semantics.timestampColumn])!, eventType: String(row[semantics.eventTypeColumn]), value: semantics.valueColumn && present(row[semantics.valueColumn]) && Number.isFinite(Number(row[semantics.valueColumn])) ? Number(row[semantics.valueColumn]) : null }));
}
const sortedEvents = (events: NormalizedEvent[]) => [...events].sort((a, b) => a.timeMs - b.timeMs || a.sourceRow - b.sourceRow);
function groupsByEntity(events: NormalizedEvent[]): Map<string, NormalizedEvent[]> { const groups = new Map<string, NormalizedEvent[]>(); for (const event of events) groups.set(event.entityId, [...(groups.get(event.entityId) ?? []), event]); for (const [id, group] of groups) groups.set(id, sortedEvents(group)); return groups; }
function temporalRuns(events: NormalizedEvent[], minimum: number): NormalizedEvent[][] { const runs: NormalizedEvent[][] = []; let current: NormalizedEvent[] = []; for (const event of sortedEvents(events)) { if (!current.length || event.timeMs - current[current.length - 1].timeMs <= EVENT_WINDOW_MS) current.push(event); else { if (current.length >= minimum) runs.push(current); current = [event]; } } if (current.length >= minimum) runs.push(current); return runs; }
const eventGroup = (id: string, events: NormalizedEvent[]): EventGroup => ({ id, entityId: events[0].entityId, eventIds: events.map((item) => item.eventId), sourceRows: events.map((item) => item.sourceRow), eventTypes: [...new Set(events.map((item) => item.eventType))].sort(), startTimestamp: events[0].timestamp, endTimestamp: events[events.length - 1].timestamp, durationMs: events[events.length - 1].timeMs - events[0].timeMs });

export function summarizeEventTypes(events: NormalizedEvent[]) { const counts = new Map<string, number>(); for (const event of events) counts.set(event.eventType, (counts.get(event.eventType) ?? 0) + 1); return [...counts].map(([eventType, count]) => ({ eventType, count, share: round(count / events.length) })).sort((a, b) => b.count - a.count || a.eventType.localeCompare(b.eventType)); }
export function summarizeEntityActivity(events: NormalizedEvent[]): EntityActivity[] { return [...groupsByEntity(events)].map(([entityId, group]) => ({ entityId, eventCount: group.length, sourceRows: group.map((item) => item.sourceRow), firstTimestamp: group[0].timestamp, lastTimestamp: group[group.length - 1].timestamp, timeSpanMs: group[group.length - 1].timeMs - group[0].timeMs, eventTypes: [...new Set(group.map((item) => item.eventType))].sort() })).sort((a, b) => b.eventCount - a.eventCount || a.entityId.localeCompare(b.entityId)); }
export function detectBursts(events: NormalizedEvent[]): EventGroup[] { let index = 1; return [...groupsByEntity(events)].sort(([a], [b]) => a.localeCompare(b)).flatMap(([, group]) => temporalRuns(group, 3).map((run) => eventGroup(`B-${String(index++).padStart(3, "0")}`, run))); }
export function detectRepeatedPatterns(events: NormalizedEvent[]): RepeatedPattern[] { const signatures = new Map<string, NormalizedEvent[]>(); for (const event of events) { const signature = `${event.entityId}|${event.eventType}|${event.value === null ? "NO_VALUE" : event.value}`; signatures.set(signature, [...(signatures.get(signature) ?? []), event]); } let index = 1; return [...signatures].sort(([a], [b]) => a.localeCompare(b)).flatMap(([signature, group]) => temporalRuns(group, 2).map((run) => ({ ...eventGroup(`R-${String(index++).padStart(3, "0")}`, run), signature, count: run.length }))); }
export function groupRelatedEvents(events: NormalizedEvent[]): EventGroup[] { let index = 1; return [...groupsByEntity(events)].sort(([a], [b]) => a.localeCompare(b)).flatMap(([, group]) => temporalRuns(group, 2).map((run) => eventGroup(`C-${String(index++).padStart(3, "0")}`, run))); }
export function inspectEventRecord(dataset: UploadedDataset, eventId: string): NormalizedEvent | undefined { return normalizeEvents(dataset).find((event) => event.eventId === eventId); }
export function inspectEntityActivity(analysis: EventTransactionAnalysis, entityId: string) { const activity = analysis.entityActivity.find((item) => item.entityId === entityId); if (!activity) return undefined; return { ...activity, notableEvents: analysis.detection.notableEvents.filter((item) => item.entityId === entityId), clusters: analysis.clusters.filter((item) => item.entityId === entityId), reasons: analysis.highlightedEntities.find((item) => item.entityId === entityId)?.reasons ?? [] }; }

export function analyzeEventTransactions(dataset: UploadedDataset): EventTransactionAnalysis {
  const semantics = resolveEventSemantics(dataset), events = normalizeEvents(dataset, semantics), ordered = sortedEvents(events), eventTypes = summarizeEventTypes(events), entityActivity = summarizeEntityActivity(events), bursts = detectBursts(events), repeatedPatterns = detectRepeatedPatterns(events), clusters = groupRelatedEvents(events);
  const eventIds = events.map((item) => item.eventId), entityCounts = entityActivity.map((item) => item.eventCount), rareTypeMaximumCount = Math.max(1, Math.floor(events.length * 0.05)), rareEventTypes = eventTypes.filter((item) => item.count <= rareTypeMaximumCount).map((item) => item.eventType);
  const values = events.flatMap((item) => item.value === null ? [] : [item.value]); const q1 = values.length >= 4 ? percentile(values, 0.25) : null, q3 = values.length >= 4 ? percentile(values, 0.75) : null, iqr = q1 === null || q3 === null ? null : q3 - q1; const valueBounds = iqr === null ? null : { lower: round(q1! - 1.5 * iqr), upper: round(q3! + 1.5 * iqr) }; const valueOutlierEventIds = valueBounds ? events.filter((item) => item.value !== null && (item.value < valueBounds.lower || item.value > valueBounds.upper)).map((item) => item.eventId) : [];
  const burstIds = new Set(bursts.flatMap((item) => item.eventIds)), repeatIds = new Set(repeatedPatterns.flatMap((item) => item.eventIds)), outlierIds = new Set(valueOutlierEventIds), rareTypes = new Set(rareEventTypes);
  const notableEvents = events.flatMap((event) => { const reasons = [...(rareTypes.has(event.eventType) ? [`тип события «${event.eventType}» встречается не чаще опубликованного порога 5%`] : []), ...(outlierIds.has(event.eventId) ? ["значение выходит за опубликованные границы 1.5×IQR"] : []), ...(burstIds.has(event.eventId) ? ["событие входит в скопление одной сущности минимум из трёх событий с промежутками не более пяти минут"] : []), ...(repeatIds.has(event.eventId) ? ["событие повторяет ту же сущность/тип/значение в течение пяти минут"] : [])]; return reasons.length ? [{ eventId: event.eventId, sourceRow: event.sourceRow, entityId: event.entityId, timestamp: event.timestamp, eventType: event.eventType, value: event.value, reasons, evidenceRefs: ["E-006"] }] : []; });
  const notableByEntity = new Map<string, number>(); for (const event of notableEvents) notableByEntity.set(event.entityId, (notableByEntity.get(event.entityId) ?? 0) + 1); const activityMedian = median(entityCounts);
  const highlightedEntities = entityActivity.flatMap((entity) => { const reasons = [...(entity.eventCount > activityMedian ? [`число событий превышает медиану по сущностям (${activityMedian})`] : []), ...((notableByEntity.get(entity.entityId) ?? 0) > 0 ? [`содержит ${notableByEntity.get(entity.entityId)} событий, отмеченных детерминированными правилами`] : [])]; return reasons.length ? [{ ...entity, reasons, evidenceRefs: ["E-007"] }] : []; });
  const gaps = ordered.slice(1).map((item, index) => item.timeMs - ordered[index].timeMs);
  const uniqueEventIds = semantics.eventIdColumn ? new Set(eventIds).size : 0;
  return { dataset: { name: dataset.name, version: stableHash({ columns: dataset.columns, rows: dataset.rows }), eventCount: events.length }, semantics, profile: { uniqueEventIds, duplicateEventIds: semantics.eventIdColumn ? eventIds.length - uniqueEventIds : 0, uniqueEntities: new Set(events.map((item) => item.entityId)).size, invalidTimestampCount: events.filter((item) => !Number.isFinite(item.timeMs)).length, earliestTimestamp: ordered[0].timestamp, latestTimestamp: ordered[ordered.length - 1].timestamp }, eventTypes, entityActivity, timing: { validTimestampCount: ordered.length, medianGapMs: gaps.length ? median(gaps) : null, burstWindowMs: EVENT_WINDOW_MS, bursts }, detection: { rareTypeMaximumCount, rareEventTypes, valueRule: valueBounds ? "IQR_1_5" : "UNAVAILABLE", valueBounds, valueOutlierEventIds, repeatedWindowMs: EVENT_WINDOW_MS, repeatedPatterns, notableEvents }, clusters, highlightedEntities, limitations: ["Общие эвристики для событий выявляют необычную активность, а не мошенничество, атаки, сбои или причинность.", "Группировка по пять минут и пороги частоты — фиксированные аудиторские правила, а не калиброванные вероятности.", ...(events.length < 30 ? ["Малое число событий ограничивает устойчивость сравнений редкости и концентрации."] : []), ...(!semantics.entityColumn ? ["Идентификатор сущности отсутствовал; группировка по сущностям использует один общий блок ALL_EVENTS."] : []), ...(!semantics.valueColumn ? ["Числовое поле суммы/значения отсутствовало; проверка выбросов по значению не выполнялась."] : [])] };
}
